import { z } from 'zod';
import {
  id,
  ids,
  key,
  text,
  scope,
  revision,
  hash,
  timestamp,
  source,
  freshness,
  evidenceClass,
  profile,
  route,
  errorCode,
} from './common.js';
import { coverage, view, locatorHint } from './capture.js';
import { verb, safeInput, guards, outcome } from './operations.js';

const common = {
  id,
  name: text,
  scope,
  evidence: z.strictObject({
    evidence_ids: ids,
    provenance: evidenceClass,
    coverage,
    freshness,
  }),
};
export const recordSummary = z.discriminatedUnion('kind', [
  z.strictObject({
    ...common,
    kind: z.literal('screen'),
    route_template: route,
    creation_revision: revision,
  }),
  z.strictObject({
    ...common,
    kind: z.literal('state'),
    screen_id: id,
    state_hash: hash,
    normalization_version: key,
    view,
  }),
  z.strictObject({
    ...common,
    kind: z.literal('control'),
    state_id: id,
    role: key,
    enabled: z.boolean(),
    visible: z.boolean(),
    descriptor: text,
    locator_hint: locatorHint.optional(),
  }),
  z.strictObject({
    ...common,
    kind: z.literal('action'),
    state_id: id,
    control_id: id.nullable(),
    verb,
    input_schema: safeInput,
    preconditions: guards,
  }),
  z.strictObject({
    ...common,
    kind: z.literal('transition'),
    source_state_id: id,
    action_id: id,
    target_state_id: id,
    before_capture_id: id,
    after_capture_id: id,
    action_event_id: id,
    outcome,
    guards,
  }),
  z.strictObject({
    ...common,
    kind: z.literal('flow'),
    transition_ids: z.array(id).min(1).max(100),
  }),
  z.strictObject({
    ...common,
    kind: z.literal('capture'),
    screen_id: id,
    state_id: id.nullable(),
    request_id: key,
    trace_id: key,
    trace_seq: z.number().int().nonnegative(),
    session_id: key,
    tab_id: key,
    captured_at: timestamp,
    received_at: timestamp,
    source,
    redaction_profile: profile,
  }),
  z.strictObject({
    ...common,
    kind: z.literal('action_event'),
    action_id: id,
    before_capture_id: id,
    after_capture_id: id.nullable(),
    trace_id: key,
    trace_seq: z.number().int().nonnegative(),
    session_id: key,
    tab_id: key,
    occurred_at: timestamp,
    outcome,
    error_code: errorCode.nullable(),
  }),
  z.strictObject({
    ...common,
    kind: z.literal('test_run'),
    runner: key,
    runner_version: key,
    application_version: text,
    started_at: timestamp,
    finished_at: timestamp,
    outcome: z.enum(['passed', 'failed', 'skipped']),
    assertions: z
      .array(
        z.strictObject({
          target_id: id,
          assertion: text,
          result: z.enum(['passed', 'failed', 'skipped']),
          evidence_ids: ids.min(1),
        }),
      )
      .min(1)
      .max(100),
  }),
  z.strictObject({
    ...common,
    kind: z.literal('annotation'),
    target_id: id,
    annotation_kind: z.enum([
      'name',
      'tag',
      'description',
      'prerequisite',
      'interpretation',
    ]),
    value: text,
    author_type: z.enum(['agent', 'human']),
    revision,
    supersedes_id: id.nullable(),
  }),
]);
